[package]
name = "azure_jwt"
version = "0.1.6"
authors = ["Carl Fredrik Samson <cf@samson.no>"]
edition = "2018"
repository = "https://github.com/cfsamson/azure-jwt"
documentation = "https://docs.rs/azure-jwt/"
readme = "README.md"
license = "MIT"
keywords = ["azure", "token", "jwt", "jwk", "validation"]
categories = ["authentication"]
description = """
A simple JWT validator for Microsoft Azure Id tokens.
"""

[dependencies]
jsonwebtoken = "7.1.0"
reqwest = "0.9.14"
serde = {version="1.0.90", features=["derive"]}
chrono = "0.4.6"
base64 = "0.10.1"

openssl_std = {package="openssl", version="0.10.20", optional=true}
openssl_vendored = {package="openssl",  version="0.10.20", features=["vendored"], optional=true}

[target.'cfg(windows)'.dependencies]
openssl-probe = "0.1.2"

[features]
default = ["openssl_std"]
vendored = ["openssl_vendored"]


[dev-dependencies]
criterion = "0.1.2"

[[bench]]
name = "validation"
harness = false
